name: Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm publish --provenance --dry-run
