name: Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v6.0.2

      - name: Install emscripten
        run: |
          sudo git clone https://github.com/emscripten-core/emsdk /opt/emsdk
          cd /opt/emsdk
          sudo ./emsdk install latest
          sudo ./emsdk activate latest
          echo "/opt/emsdk" >> $GITHUB_PATH
          echo "/opt/emsdk/upstream/emscripten" >> $GITHUB_PATH
          echo "EM_CACHE=$HOME/.emscripten_cache" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable PNPM
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish --provenance --no-git-checks
